# Generated by Django 2.0.1 on 2018-01-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative_p', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cat_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Computer Science', max_length=200),
        ),
    ]
